namespace GymApis.Models.Members;

/// <summary>
/// Keyless read model over the `v_payment_ledger` view (010_payments_module.sql).
///
/// One row per payment, joined to the member, the membership, the plan and
/// v_membership_balance. The view owns those joins for the same reason
/// v_member_overview owns the members list's: a Balance Due assembled in LINQ
/// here would be a second implementation of an arithmetic the schema already
/// performs, and the two would drift.
///
/// Two properties that mean less than their names suggest:
///
///  * <see cref="BalanceAmount"/> is the MEMBERSHIP's outstanding balance,
///    repeated on every instalment row against it — not what was left after
///    this particular payment. The schema forbids storing a per-payment
///    remainder by name (schema_v1.sql:399).
///
///  * <see cref="Status"/> is the transaction's own state
///    (completed | pending | failed | refunded), while
///    <see cref="PaymentStatus"/> is what v_membership_balance derives about
///    the membership (paid | partial | pending). Two vocabularies, not the same
///    word — the trap members.status and membership_state already set.
///
/// Keyless means EF will not track or write it. Reads only.
/// </summary>
public class PaymentLedger
{
    public long Id { get; set; }
    public long TenantId { get; set; }
    public long BranchId { get; set; }

    /// <summary>RCP-000001. Generated by the payments table's own DEFAULT.</summary>
    public string? ReceiptNo { get; set; }

    public long MemberId { get; set; }
    public string MemberCode { get; set; } = default!;

    /// <summary>
    /// "Deleted member" for an erased one — EraseAsync overwrites the name and
    /// keeps the code, so this join never carries personal data it should not.
    /// </summary>
    public string MemberName { get; set; } = default!;
    public string Phone { get; set; } = default!;

    // Null for a payment whose membership was deleted, and for purposes that
    // never had one (merchandise, registration). Plan, expiry and balance are
    // LEFT JOINed off it and go null together.
    public long? MembershipId { get; set; }
    public long? PlanId { get; set; }
    public string? PlanName { get; set; }
    public DateOnly? EndDate { get; set; }

    public DateTimeOffset PaidAt { get; set; }
    public decimal Amount { get; set; }

    /// <summary>The membership's outstanding balance, not this payment's.</summary>
    public decimal? BalanceAmount { get; set; }

    /// <summary>paid | partial | pending. The membership's, derived by the view.</summary>
    public string? PaymentStatus { get; set; }

    public string Method { get; set; } = default!;

    /// <summary>completed | pending | failed | refunded. This row's own.</summary>
    public string Status { get; set; } = default!;

    public string Purpose { get; set; } = default!;
    public string? ReferenceNo { get; set; }
}
